FROM node:20

EXPOSE 8080

ENV DB_HOST=mysql

RUN useradd -m expense

WORKDIR /opt/server

COPY package.json .

RUN npm install

COPY *.js .

RUN chown -R expense:expense /opt/server

USER expense

CMD ["node", "index.js"]